### Criar um novo produto

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXIiOiJndWlsaGVybWVsdWFucHJvZHV0b3IxMUBwbS5tZSIsInJvbGUiOiJwcm9kdXRvciIsImlhdCI6MTc0ODM2NjM2OSwiZXhwIjoxNzQ4MzY5OTY5fQ.FZ5jpk5om4yChId6-JuMASSdjC4T6daH4JLdpcBqpbY

{
  "name": "Banana",
  "description": "Banana orgânica e fresca",
  "price": 5.99,
  "imageUrl": "https://example.com/images/maca_gala.jpg",
  "rating": 4.5,
  "category": "Fruta",
  "storeId": 1
}

### Buscar todos os produtos
GET http://localhost:3000/products

### Buscar um produto pelo ID
GET http://localhost:3000/products/1

### Atualizar um produto
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Maçã Fuji",
  "price": 6.50
}

### Deletar um produto
DELETE http://localhost:3000/products/1

### Buscar produtos de uma loja pelo ID da loja
GET http://localhost:3000/store/1/products