### Criar uma nova loja
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXIiOiJndWlsaGVybWVsdWFucHJvZHV0b3IxMUBwbS5tZSIsInJvbGUiOiJwcm9kdXRvciIsImlhdCI6MTc0ODg2MzE3OCwiZXhwIjoxNzQ4ODY2Nzc4fQ.vsoLIsegjZ6JyXEdDkeDPpNP36cpRsJ40qkZ7Fs9NlA

POST http://localhost:3000/store
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "name": "Loja do Zé",
  "description": "Frutas e verduras frescas direto da horta.",
  "producerProfileId": 1
}

### Buscar todas as lojas
GET http://localhost:3000/store
//Authorization: Bearer {{token}} // Adicione o token de autenticação aqui

### Buscar uma loja pelo ID
GET http://localhost:3000/store/1
//Authorization: Bearer {{token}} // Adicione o token de autenticação aqui

### Atualizar uma loja
PATCH http://localhost:3000/store/1
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "name": "Loja do Zé Atualizada",
  "description": "As melhores frutas e verduras da região.",
  "rating": 4.5
}

### Deletar uma loja
DELETE http://localhost:3000/store/1
//Authorization: Bearer {{token}} // Adicione o token de autenticação aqui

### Buscar produtos de uma loja pelo ID da loja
GET http://localhost:3000/store/1/products