### Realizar cadastro
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Guilherme Luan",
  "email": "guilhermeadad@pm.me",
  "password": "teste123456444447",
  "role": "cliente",
  "cpf": "1234566781"
}

### Realizar login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "guilhermeadad@pm.me",
  "password": "teste123456444447"
}

### Buscar usuários
GET http://localhost:3000/user


### Buscar usuário pelo email (sem encoding)
GET http://localhost:3000/user?email=guilherme@pm.me

### Buscar usuário pelo id
GET http://localhost:3000/user/2

### Modifcar
PATCH http://localhost:3000/user/2
Content-Type: application/json

{
  "name": "Guilherme Luan Reis"
}

### Deletar usuario
DELETE http://localhost:3000/user/1

